project:
  type: website

website:
  title: "home"
  site-url: https://eddyofastro.github.io
  description: "Edwards Taufiqurrahman personal web"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/eddyofastro
      - icon: twitter
        href: https://twitter.com/edskywalker
format:
  html:
    theme: flatly
    css: styles.css



